Africa/Pages/Error.cshtml.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;

namespace Africa.Pages
{
    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    [IgnoreAntiforgeryToken]
    public class ErrorModel : PageModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

        private readonly ILogger<ErrorModel> _logger;

        public ErrorModel(ILogger<ErrorModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
            RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
        }
    }
}

Africa/Pages/Galery/Editar.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Africa.Modelo;
using Africa.Servicios;

namespace MyApp.Namespace
{
    public class EditarModel : PageModel
    {
        [BindProperty]
        public Ropa RopaEditar { get; set; }
        private IRopaServicio _ropaServicio;

        public EditarModel(IRopaServicio ropaServicio)
        {
            _ropaServicio = ropaServicio;
        }
        public void OnGet(int id)
        {
            RopaEditar = _ropaServicio.MostrarTodos().Where(x => x.ID == id).First();
        }
        public IActionResult OnPost()
        {
            _ropaServicio.Modificar(RopaEditar);
            return RedirectToPage("Galeria");
        }
    }
}

Africa/Pages/Galery/Galeria.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Africa.Servicios;
using Africa.Modelo;

namespace Africa.Pages
{
    public class GaleriaModel : PageModel
    {
        [BindProperty]
        public List<Ropa> Ropas { get; set; }

        private IRopaServicio _ropaServicio;

        public GaleriaModel(IRopaServicio ropaServicio)
        {
            _ropaServicio = ropaServicio;
        }

        public void OnGet(string orden)
        {
            Ropas = _ropaServicio.MostrarTodos().ToList();
            if (orden == "PorNombre")
            {
                Ropas = Ropas.OrderBy(x => x.NombrePrenda).ToList();
            }
            else if (orden == "PorPrenda")
            {
                Ropas = Ropas.OrderBy(x => x.Prenda).ToList();
            }
            else if (orden == "PorCantidad")
            {
                Ropas = Ropas.OrderBy(x => x.CantidadStock).ToList();
            }
            else
            {
                Ropas = Ropas.OrderBy(x => x.ID).ToList();
            }

        }
        public IActionResult OnPost()
        {
            return RedirectToPage("Ingresar");
        }

        public void OnGetEliminar(int IDEliminar)
        {
            var ropaBorrar = _ropaServicio.MostrarTodos().Where(x => x.ID == IDEliminar).First();
            _ropaServicio.Eliminar(ropaBorrar);
            Ropas = _ropaServicio.MostrarTodos().ToList();

        }
        public void OnPostBuscar(string PrendaBuscar)
        {
            if (PrendaBuscar == null)
            {
                Ropas = _ropaServicio.MostrarTodos().ToList();
            }
            else
            {
                Ropas = _ropaServicio.MostrarTodos().Where(x => x.Prenda == PrendaBuscar).ToList();
            }
        }
    }
}

Africa/Pages/Galery/Ingresar.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Africa.Servicios;
using Africa.Modelo;

namespace Africa.Pages
{
    public class IngresarModel : PageModel
    {
        [BindProperty]
        public Ropa RopaNuevo { get; set; }
        private IRopaServicio _ropaServicio;

        public IngresarModel(IRopaServicio ropaServicio)
        {
            _ropaServicio = ropaServicio;
        }
        public void OnGet()
        {
        }
        public IActionResult OnPost()
        {
            if (ModelState.IsValid)
            {
                _ropaServicio.Agregar(RopaNuevo);
                return RedirectToPage("Galeria");
            }

            return Page();

        }
    }
}

Africa/Pages/Index.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;

namespace Africa.Pages
{
    public class IndexModel : PageModel
    {
        private readonly ILogger<IndexModel> _logger;

        public IndexModel(ILogger<IndexModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {

        }
    }
}

Africa/Pages/Privacy.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;

namespace Africa.Pages
{
    public class PrivacyModel : PageModel
    {
        private readonly ILogger<PrivacyModel> _logger;

        public PrivacyModel(ILogger<PrivacyModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
        }
    }
}

Africa/Pages/Galery/Editar.cshtml
@page
@model MyApp.Namespace.EditarModel
@{
}
<partial name="_FormGaleria" model="@Model.RopaEditar" />

Africa/Pages/Galery/Galeria.cshtml
@page
@model Africa.Pages.GaleriaModel
@{
}
<h2>Lista de Articulos</h2>
<partial name="_Lista" model="@Model.Ropas" />

Africa/Pages/Galery/Ingresar.cshtml
@page
@model Africa.Pages.IngresarModel
@{
}
@section scripts{
<partial name="_ValidationScriptsPartial" />
}

<partial name="_FormGaleria" model="@Model.RopaNuevo" />

Africa/Pages/Index.cshtml
@page
@model IndexModel
@{
    ViewData["Title"] = "Home page";
}

<div class="text-center">
    <img src="~/Fotos/Africa.jpg" alt="Fondo" class="img-fluid" width="100%">
</div>
<br>
<hr>
<br>
<br>
<hr>
<div class="conteiner">
    <h2 class="titulo">Instrucciones</h2>
    <p>
    <h5 class="titulo">¡Bienvenido!</h5>
    <br>

    Ésta es una página de control de Stock. En ella podras <strong>Ingresas</strong>, <strong>Modificar</strong>,
    <strong>Ver</strong> y <strong>Eliminar</strong>
    Productos de tu tienda.

    <ul>
        <li>
            Al agregar un articulo es importante que completes todos los campos. (El campo de cantidad de productos
            puede obviarse.)
        </li>
        <li>
            Luego de agregar tus productos, podras verlos en la pestaña de <strong>Galery</strong>.
        </li>
        <li>
            En la Galeria podras encontrar una barra de busqueda. Ésta misma busca por Prenda, si decea volver a ver
            toda la lista, simplemente deje el campo en blanco.
            Tambien podras ver que a la derecha de cada articulo se encuentran los botones <strong>Editar</strong> y
            <strong>Eliminar</strong>. Es importante corroborar que el elemento a editar o eliminar sea el indicado.
        </li>
    </ul>

    </p>
</div>
<br>
<hr>
<br>
<br>
<hr>

Africa/Pages/Shared/_FormGaleria.cshtml
@model Africa.Modelo.Ropa

@if (@Model == null || @Model.ID == 0)
{
    <h3>INGRESE UN ARTICULO</h3>
}
else
{
    <h3>MODIFICAR ARTICULO: <span>@Model.ID</span></h3>

}

<form method="post">
    <div class="form-group">
        <input type="text " asp-for="@Model.ID" placeholder="Ingresar ID de la prenda.">
        <span asp-validation-for="@Model.ID" class="badge badge-danger"></span>
    </div>

    <div class="form-group">
        <input type="text " asp-for="@Model.NombrePrenda" placeholder="Ingresar el nombre de la prenda.">
        <span asp-validation-for="@Model.NombrePrenda" class="badge badge-danger"></span>
    </div>

    <div class="form-group">
        <input type="text " asp-for="@Model.Prenda" placeholder="Ingresar tipo de prenda.">
        <span asp-validation-for="@Model.Prenda" class="badge badge-danger"></span>
    </div>

    <div class="form-group">
        <input type="text " asp-for="@Model.CantidadStock" placeholder="Ingresar cantidad de prendas.">

    </div>
    <input type="submit" value="Guardar" class="btn btn-dark">
    <a asp-page="Galeria" class="btn btn-secondary"
        onclick="return confirm('¿Esta seguro que decea volver sin guardar?')">Volver</a>

</form>

Africa/Pages/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Africa</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" href="~/css/cssnav.css" />
</head>

<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-page="/Index" text-aling="Left"><img src="~/Fotos/Africa1.jpg"
                        alt="Fondo" class="img-fluid" width="5%"></a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse"
                    aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-page="/Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-page="/Galery/Galeria">Galery</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-page="/Galery/Ingresar">New</a>
                        </li>
                        @* <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-page="/Privacy">Privacy</a>
                            </li> *@
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="footer  footer-dark ">
        <div class="container">
            <div class="row">
                <div class="col-sm-6 col-md-3 item">
                    <h3>Services</h3>
                    <ul>
                        <li><a href="#">Web design</a></li>
                        <li><a href="#">Development</a></li>
                        <li><a href="#">Hosting</a></li>
                    </ul>
                </div>
                <div class="col-sm-6 col-md-3 item">
                    <h3>About</h3>
                    <ul>
                        <li><a href="#">Company</a></li>
                        <li><a href="#">Team</a></li>
                        <li><a href="#">Careers</a></li>
                    </ul>
                </div>
                <div class="col-md-6 item text">
                    <h3>Domus Joinery</h3>
                    <p>Somos una Empresa dedicada a crear paginas web funcionales. Aca dejamos una muestra de nuestro
                        trabajo, esperamos que les guste y lo disfruten.</p>
                </div>
            </div>
            <p class="copyright">Africa © 2018 <a asp-area="" asp-page="/Privacy">Privacy</a></p>
        </div>
    </footer>



    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @await RenderSectionAsync("Scripts", required: false)
</body>

</html>

Africa/Pages/Shared/_Lista.cshtml
@model List<Africa.Modelo.Ropa>
@{
}
<form asp-page="Galeria" method="post" asp-page-handler="Buscar">
    <input type="text" name="PrendaBuscar" placeholder="Buscar por Prenda" />
    <input type="submit" class="btn btn-warning" value="Buscar" />
</form>

<br>
<div class="table-responsive">
    <table class="table table-dark" class="table align-middle">
        <thead>
            <tr>
                <th class="text-center"><a asp-page="./Galeria" asp-route-orden="PorID" class="btn btn-dark">ID</a></th>
                <th class="text-center"><a asp-page="./Galeria" asp-route-orden="PorNombre"
                        class="btn btn-dark">Nombre</a></th>
                <th class="text-center"><a asp-page="./Galeria" asp-route-orden="PorPrenda"
                        class="btn btn-dark">Prenda</a></th>
                <th class="text-center"><a asp-page="./Galeria" asp-route-orden="PorCantidad"
                        class="btn btn-dark">Stock</a></th>

                <th></th>
            </tr>
        </thead>
        <tbody>
            @foreach (var rop in Model)
            {
                <tr>
                    <td class="text-center">@rop.ID</td>
                    <td class="text-center">@rop.NombrePrenda</td>
                    <td class="text-center">@rop.Prenda</td>
                    <td class="text-center">@rop.CantidadStock</td>
                    <td class="text-center">
                        <a asp-page="./Editar" asp-route-id="@rop.ID" class="btn btn-dark">Editar</a>
                        |
                        <a asp-page="Galeria" asp-page-handler="Eliminar" asp-route-IDEliminar="@rop.ID"
                        class="btn btn-dark"
                        onclick="return confirm('¿Esta seguro que decea eliminar esta prenda?')">Eliminar</a>
                    </td>
                </tr>
            }
        </tbody>
    </table>
    <form method="post">
        <input type="submit" value="Ingresar una Prenda" class="btn btn-dark">
    </form>
</div>